"""Continue.dev — `.continue/rules/chamnan.md`.

Frontmatter from Continue's own rules documentation: `name`, `description`, `globs`, and
`alwaysApply`. `alwaysApply: true` means the rule is always in the system message; false means it
is included only when `globs` matches the file in context. Rules are joined with newlines in
toolbar order.

`globs` is deliberately omitted rather than set to `**`. With `alwaysApply: true` it is not
consulted, and writing a pattern that is never read invites the next person to change it and
wonder why nothing happened.

Continue has a hooks system with a SessionStart event, merged in early 2026, but it shipped ahead
of its own documentation and has no published reference. A rules file is the documented mechanism,
so that is what this writes.
"""

NAME = "continue"
TARGET = ".continue/rules/chamnan.md"
CEILING = None

_DESCRIPTION = ("What this repository is, how it is laid out, and the rules and decisions it "
                "works under. Generated by chamnan.")


def _fence_safe(text):
    """`text` with any line that is exactly `---` unable to close the frontmatter early.

    Its own copy, as in the other frontmatter adapters: four agents share this convention today,
    and one shared helper would mean a change made for one silently changing the other three.
    """
    return "\n".join("***" if line.strip() == "---" else line for line in text.splitlines())


def render(body):
    """The block as a Continue rule."""
    return (f"---\n"
            f"name: chamnan\n"
            f"description: {_DESCRIPTION}\n"
            f"alwaysApply: true\n"
            f"---\n\n"
            f"{_fence_safe(body).rstrip()}\n")
