"""Continue.dev — `.continue/rules/chamnan.md`.

Frontmatter from Continue's own rules documentation: `name`, `description`, `globs`, and
`alwaysApply`. `alwaysApply: true` means the rule is always in the system message; false means it
is included only when `globs` matches the file in context. Rules are joined with newlines in
toolbar order.

`globs` is deliberately omitted rather than set to `**`. With `alwaysApply: true` it is not
consulted, and writing a pattern that is never read invites the next person to change it and
wonder why nothing happened.

Continue has a hooks system with a SessionStart event, merged in early 2026, but it shipped ahead
of its own documentation and has no published reference. A rules file is the documented mechanism,
so that is what this writes.
"""

NAME = "continue"
# This vendor reads the root `AGENTS.md` AS WELL AS its own file, so a repository that has
# run both `--write generic` and `--write <this>` sends the identical block twice, every
# session, and pays for it twice. Declared here rather than listed in `__init__.py`:
# 🐛 [2026-09-10] that list held four names while EIGHT vendors qualified, and the evidence
# for the missing four was sitting in their own docstrings. A set kept beside the thing it
# describes cannot drift from it (R4 agent 1, finding 6).
# Evidence: docs.continue.dev/customize/deep-dives/rules — "alongside .continue/rules"
# (verified 2026-09-08).
ALSO_READS_AGENTS_MD = True

TARGET = ".continue/rules/chamnan.md"
CEILING = None

_DESCRIPTION = ("What this repository is, how it is laid out, and the rules and decisions it "
                "works under. Generated by chamnan.")


# 🐛 [2026-09-10] `_fence_safe` lived here, in six byte-identical copies, rewriting any body
# line that was exactly `---` to `***`. Its docstring said an untreated `---` "would end the
# frontmatter early, and every line after it would be read as the rule's body starting in the
# middle of a sentence" — and that cannot happen. `render()` below emits `---`, the keys, and a
# CLOSING `---` before the body is reached, so the frontmatter is shut by chamnan's own delimiter
# and a body line can no longer close anything. Verified for all six adapters.
#
# So the guard bought nothing, and it was not free. A `---` that FOLLOWS a text line is a setext
# `<h2>` underline in CommonMark; rewriting it to `***` turns somebody's heading into a paragraph
# plus a horizontal rule, which changes the outline of the document the agent is handed. The one
# real effect the function had was the one nobody wrote down (R4 agent 1, finding 10).
#
# This is not a reversal of the round that kept the six copies and policed them for divergence
# (R5 agent 3, 2026-09-06): that round asked whether the copies AGREED, and they did. It never
# asked whether the thing they agreed on was needed.
#
# What replaces it is a check over the SET rather than a guard in each member: the suite asserts
# that every frontmatter adapter closes its frontmatter before its body. An adapter that one day
# does not is told so, and can then be given a guard for the reason that is actually true.


def render(body):
    """The block as a Continue rule."""
    return (f"---\n"
            f"name: chamnan\n"
            f"description: {_DESCRIPTION}\n"
            f"alwaysApply: true\n"
            f"---\n\n"
            f"{body.rstrip()}\n")
