"""Cursor — `.cursor/rules/chamnan.mdc`.

Cursor reads project rules from `.cursor/rules/*.mdc`: markdown with a YAML-ish frontmatter block
that says when the rule applies. `alwaysApply: true` is the one that matches what chamnan's block
is for -- an orientation the agent should have before it starts, not a rule that fires on a glob.

**Not verified against a running Cursor.** Cursor was not installed on the machine this was written
on, so the format here comes from its documented convention rather than from an observed file. What
IS verified is everything this module controls: that the frontmatter is well formed, that the block
survives being wrapped in it, and that a body containing `---` cannot end the frontmatter early.
Where that line is drawn is stated so the next person does not have to guess which half was tested.

The legacy `.cursorrules` single file is deliberately not written. Cursor still reads it, and
writing both would give one repository two copies of the same context that drift apart the first
time only one of them is regenerated.
"""

NAME = "cursor"
TARGET = ".cursor/rules/chamnan.mdc"

# Cursor reads the file off disk rather than through a hook that truncates, so nothing here imposes
# a byte limit. The block's own token budgets are what bound it -- see lib/profiles.py.
CEILING = None

_DESCRIPTION = ("What this repository is, how it is laid out, and the rules and decisions it "
                "works under. Generated by chamnan; do not edit by hand.")


# 🐛 [2026-09-10] `_fence_safe` lived here, in six byte-identical copies, rewriting any body
# line that was exactly `---` to `***`. Its docstring said an untreated `---` "would end the
# frontmatter early, and every line after it would be read as the rule's body starting in the
# middle of a sentence" — and that cannot happen. `render()` below emits `---`, the keys, and a
# CLOSING `---` before the body is reached, so the frontmatter is shut by chamnan's own delimiter
# and a body line can no longer close anything. Verified for all six adapters.
#
# So the guard bought nothing, and it was not free. A `---` that FOLLOWS a text line is a setext
# `<h2>` underline in CommonMark; rewriting it to `***` turns somebody's heading into a paragraph
# plus a horizontal rule, which changes the outline of the document the agent is handed. The one
# real effect the function had was the one nobody wrote down (R4 agent 1, 2026-09-10, finding 10).
#
# This is not a reversal of the round that kept the six copies and policed them for divergence
# (R5 agent 3, 2026-09-06): that round asked whether the copies AGREED, and they did. It never
# asked whether the thing they agreed on was needed.
#
# What replaces it is a check over the SET rather than a guard in each member: the suite asserts
# that every frontmatter adapter closes its frontmatter before its body. An adapter that one day
# does not is told so, and can then be given a guard for the reason that is actually true.


def render(body):
    """The block as a Cursor rule file."""
    return (f"---\n"
            f"description: {_DESCRIPTION}\n"
            f"alwaysApply: true\n"
            f"---\n\n"
            f"{body.rstrip()}\n")
