"""Cursor — `.cursor/rules/chamnan.mdc`.

Cursor reads project rules from `.cursor/rules/*.mdc`: markdown with a YAML-ish frontmatter block
that says when the rule applies. `alwaysApply: true` is the one that matches what chamnan's block
is for -- an orientation the agent should have before it starts, not a rule that fires on a glob.

**Not verified against a running Cursor.** Cursor was not installed on the machine this was written
on, so the format here comes from its documented convention rather than from an observed file. What
IS verified is everything this module controls: that the frontmatter is well formed, that the block
survives being wrapped in it, and that a body containing `---` cannot end the frontmatter early.
Where that line is drawn is stated so the next person does not have to guess which half was tested.

The legacy `.cursorrules` single file is deliberately not written. Cursor still reads it, and
writing both would give one repository two copies of the same context that drift apart the first
time only one of them is regenerated.
"""

NAME = "cursor"
TARGET = ".cursor/rules/chamnan.mdc"

# Cursor reads the file off disk rather than through a hook that truncates, so nothing here imposes
# a byte limit. The block's own token budgets are what bound it -- see lib/profiles.py.
CEILING = None

_DESCRIPTION = ("What this repository is, how it is laid out, and the rules and decisions it "
                "works under. Generated by chamnan; do not edit by hand.")


def _fence_safe(text):
    """`text` with any line that is exactly `---` made incapable of closing the frontmatter.

    A YAML frontmatter block ends at the first line that is exactly three dashes, and this block
    carries repository-authored prose -- a horizontal rule in somebody's rule file is ordinary
    markdown and entirely likely. Left alone it would end the frontmatter early, and every line
    after it would be read as the rule's body starting in the middle of a sentence.

    Rewritten to the other markdown horizontal rule rather than removed: `***` renders identically
    and means the same thing to a reader, so nothing is lost that the writer intended.
    """
    return "\n".join("***" if line.strip() == "---" else line for line in text.splitlines())


def render(body):
    """The block as a Cursor rule file."""
    return (f"---\n"
            f"description: {_DESCRIPTION}\n"
            f"alwaysApply: true\n"
            f"---\n\n"
            f"{_fence_safe(body).rstrip()}\n")
