"""The cross-tool convention — `AGENTS.md`, edited in place rather than written over.

`AGENTS.md` is what an agent with no adapter of its own gets, and it is the one target here that a
person is most likely to have written themselves. Overwriting it would delete somebody's own
instructions to their own agents, which is a worse outcome than not being installed at all.

So this adapter owns its install and edits between two markers:

    <!-- chamnan:start --> ... <!-- chamnan:end -->

Everything outside them is theirs and is returned byte for byte. Re-running replaces only what is
between them. If the markers are absent, the region is appended once, after their text, because
what they wrote is the more specific instruction and should be read last.

**HTML comments, not a frontmatter block or a heading.** A heading would appear in their document's
outline as if they had written it; a comment is invisible in every renderer and unambiguous to the
next person who opens the file.
"""

NAME = "generic"
TARGET = "AGENTS.md"
CEILING = None

START = "<!-- chamnan:start -->"
END = "<!-- chamnan:end -->"

_NOTE = ("<!-- Everything between these two markers is generated by chamnan and is replaced on "
         "every run. Edit outside them. -->")


def render(body):
    """The block wrapped in its markers, ready to be dropped into a larger document."""
    return f"{START}\n{_NOTE}\n\n{body.rstrip()}\n{END}\n"


def install(root, body, command=""):
    """Replace chamnan's region in `AGENTS.md`, leaving every other byte of it alone.

    `command` is unused: this adapter writes text now rather than registering something to run
    later. It is in the signature because that is the one shape every adapter's install has.

    A file whose START marker has no matching END is REFUSED rather than repaired. Two guesses are
    available -- treat the rest of the file as chamnan's and delete it, or insert an END somewhere
    -- and both can destroy text somebody wrote. Saying so and stopping is the only option that
    cannot.
    """
    import workspace as ws

    path = ws.Path(root) / TARGET
    region = render(body)
    if not path.exists():
        ws.atomic_write_text(path, region)
        return path

    existing = path.read_text(encoding="utf-8")
    head, marked, rest = existing.partition(START)
    if not marked:
        joined = existing.rstrip() + "\n\n" + region
        ws.atomic_write_text(path, joined)
        return path

    _ours, closed, tail = rest.partition(END)
    if not closed:
        raise ValueError(f"{path} opens a chamnan region and never closes it; "
                         f"refusing to guess where it was meant to end")
    # One blank line between the region and whatever they wrote after it. Without it their next
    # heading butts against the end marker, which renders in most parsers but reads as damage in
    # the diff -- and this file is one a person opens by hand.
    after = tail.lstrip("\n")
    ws.atomic_write_text(path, head + region + ("\n" + after if after else ""))
    return path
