"""Trae (ByteDance) — `.trae/rules/project_rules.md`.

Trae reads EVERY `.md` under `.trae/rules/`, not one reserved name: its own documentation walks a
user through creating `ci-rules.md`, `general-rules.md` and others, and the scan is recursive to
three levels for subdirectory scope. So `project_rules.md` is chamnan's choice of
filename, and an earlier version of this docstring, which said Trae "reads one specific name", was
wrong about the vendor rather than about the code (R7/R8 agent 1, checked against docs.trae.ai).

That earlier version also said the chosen name "cannot collide with a rule file the repository
already had", and that was wrong in the other direction: `project_rules.md` is the name Trae's own
documentation walks a user through creating, so it is the ONE name in that directory most likely to
be taken. See the paragraph below for what happens when it is — and note that the correction here
and the correction there had to be made together, because a fix to one paragraph that leaves its
sibling standing is how this file came to say two different things in the first place. Its frontmatter keys are `alwaysApply`,
`globs` and `description` -- the same three Cursor uses, which is not a coincidence and is not a
reason to share code with it either.

**The filename is chamnan's choice, and a user may plausibly have made the same one.** Every other
file adapter writes `chamnan.md` alongside whatever else is in the directory; this one writes
`project_rules.md`, which is the name Trae's own documentation walks a user through creating. So
this adapter can want a file somebody already wrote.

That is handled, and not here: the shared writer in `__init__.py` refuses to replace a target that
does not itself begin as chamnan output, so a hand-written `project_rules.md` is left alone and the
command fails loudly. There is no marker-region merge because there does not need to be one.

🐛 [2026-09-08] This paragraph used to open "**The filename is fixed** ... Trae reads one specific
name", and end "if they had one, it is replaced". Both halves were false by then and both had
already been corrected elsewhere: the vendor fact two paragraphs above (Trae reads EVERY `.md`
under `.trae/rules/`), and the overwrite behaviour in `__init__.py`'s shared writer. Each fix
landed BESIDE the claim it retracted rather than over it, so a reader who stopped at paragraph one
got the right answer and a reader who continued to the design rationale got the wrong one, with a
justification built on it (R8 agent 1).
"""

NAME = "trae"
TARGET = ".trae/rules/project_rules.md"
CEILING = None


# 🐛 [2026-09-10] `_fence_safe` lived here, in six byte-identical copies, rewriting any body
# line that was exactly `---` to `***`. Its docstring said an untreated `---` "would end the
# frontmatter early, and every line after it would be read as the rule's body starting in the
# middle of a sentence" — and that cannot happen. `render()` below emits `---`, the keys, and a
# CLOSING `---` before the body is reached, so the frontmatter is shut by chamnan's own delimiter
# and a body line can no longer close anything. Verified for all six adapters.
#
# So the guard bought nothing, and it was not free. A `---` that FOLLOWS a text line is a setext
# `<h2>` underline in CommonMark; rewriting it to `***` turns somebody's heading into a paragraph
# plus a horizontal rule, which changes the outline of the document the agent is handed. The one
# real effect the function had was the one nobody wrote down (R4 agent 1, finding 10).
#
# This is not a reversal of the round that kept the six copies and policed them for divergence
# (R5 agent 3, 2026-09-06): that round asked whether the copies AGREED, and they did. It never
# asked whether the thing they agreed on was needed.
#
# What replaces it is a check over the SET rather than a guard in each member: the suite asserts
# that every frontmatter adapter closes its frontmatter before its body. An adapter that one day
# does not is told so, and can then be given a guard for the reason that is actually true.


def render(body):
    """The block as a Trae project rule."""
    return (f"---\n"
            f"alwaysApply: true\n"
            f"description: Generated by chamnan — what this repository is and the rules it works under.\n"
            f"---\n\n"
            f"{body.rstrip()}\n")
