"""Trae (ByteDance) — `.trae/rules/project_rules.md`.

Trae reads `project_rules.md` from `.trae/rules/` at the project root, and from nested `.trae/rules/`
directories up to three levels deep for subdirectory scope. Its frontmatter keys are `alwaysApply`,
`globs` and `description` -- the same three Cursor uses, which is not a coincidence and is not a
reason to share code with it either.

**The filename is fixed, and that is the difference that matters here.** Every other file adapter
writes `chamnan.md` alongside whatever else is in the directory. Trae reads one specific name, so
this adapter owns a file a user may also want to write in themselves. There is no marker-region
merge for it, because the file is small and the honest failure is visible: if they had one, it is
replaced, and `--write trae` is not a command anyone runs by accident.
"""

NAME = "trae"
TARGET = ".trae/rules/project_rules.md"
CEILING = None


def _fence_safe(text):
    """`text` with any line that is exactly `---` unable to close the frontmatter early."""
    return "\n".join("***" if line.strip() == "---" else line for line in text.splitlines())


def render(body):
    """The block as a Trae project rule."""
    return (f"---\n"
            f"alwaysApply: true\n"
            f"description: Generated by chamnan — what this repository is and the rules it works under.\n"
            f"---\n\n"
            f"{_fence_safe(body).rstrip()}\n")
