"""What each session was actually handed, recorded as a SHAPE rather than a copy.

The block a session receives is assembled fresh every time from files that are already in git, so
storing the text again buys nothing: it can be regenerated by running the hook. What cannot be
regenerated is *what yesterday's block looked like* — and every serious defect this workspace has
had shows up in that shape rather than in the words.

Measured on this repository, 2026-09-07: the full block is 8,938 bytes and this record is 188. At
twenty sessions a day that is 62 MB a year against 1.3 MB. `tools/housekeeping.py` exists because
Claude Code's own data directories reached 950 MB unattended; a log that grows like the problem it
was written beside is not worth having, so this one is bounded by RECORD COUNT and stores no
content at all.

Three real defects from one day, and what each looks like here:

    rulecheck's glob raised out of the hook   -> "early": true, half the sections gone
    a tools index with a string `runs`        -> "bytes" drops by ~257, one section missing
    the downgrade banner lost its cap         -> "bytes" jumps to 34,728

None of those was noticed for hours. All three are obvious in a column of numbers.
"""
import json
import re

import workspace as ws

LOG = "logs/block_shape.jsonl"
KEEP = 400          # records, not days: one session a day still leaves a year of trend
NAME_CHARS = 38     # a heading is an identifier here, not prose

_SECTION = re.compile(r"^### (.+)$", re.M)


def shape(body, ceiling=None, when=None):
    """The record for one assembled block. Pure: no clock, no disk, no workspace."""
    sections = {}
    marks = list(_SECTION.finditer(body))
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(body)
        sections[m.group(1).strip()[:NAME_CHARS]] = len(body[m.start():end].encode("utf-8"))
    rec = {"bytes": len(body.encode("utf-8")), "sec": sections,
           # The hook catches every exception and ends the block with this sentence rather than
           # failing, which is right — and is exactly why the truncation went unseen for hours.
           "early": "stopped early" in body}
    if ceiling:
        rec["ceiling"] = ceiling
    if when:
        rec["t"] = when
    return rec


def record(root, body, ceiling=None, when=None):
    """Append one shape record, trimmed to KEEP. Returns True when it wrote.

    Never raises: a session that cannot write its own telemetry is still a session, and the block
    has already been assembled by the time this is called. Skips entirely when another process
    holds the lock — two sessions starting in the same second is ordinary, and a dropped record is
    a cheaper outcome than an interleaved file.
    """
    try:
        log = ws.workspace(root) / LOG
        log.parent.mkdir(parents=True, exist_ok=True)
        with ws.exclusive(log) as held:
            if not held:
                return False
            prior = []
            if log.is_file():
                for line in log.read_text(encoding="utf-8-sig", errors="replace").splitlines():
                    try:
                        one = json.loads(line)
                    except (json.JSONDecodeError, RecursionError):
                        continue
                    # A line that parses but is not an object is a half-written record; keeping it
                    # would hand every reader below an AttributeError instead of a number.
                    if isinstance(one, dict):
                        prior.append(one)
            prior.append(shape(body, ceiling, when))
            ws.atomic_write_text(
                log, "\n".join(json.dumps(r, separators=(",", ":"), ensure_ascii=False)
                                for r in prior[-KEEP:]) + "\n")
        return True
    except Exception:      # noqa: BLE001 — telemetry must never be the thing that breaks a session
        return False


def trend(root, last=10):
    """The most recent records, oldest first. For `chamnan-report`, and for a person asking
    "did something change?" — which is the only question this log exists to answer."""
    try:
        log = ws.workspace(root) / LOG
        if not log.is_file():
            return []
        out = []
        for line in log.read_text(encoding="utf-8-sig", errors="replace").splitlines():
            try:
                one = json.loads(line)
            except (json.JSONDecodeError, RecursionError):
                continue
            if isinstance(one, dict):
                out.append(one)
        return out[-last:]
    except OSError:
        return []
