"""What each session was actually handed, recorded as a SHAPE rather than a copy.

The block a session receives is assembled fresh every time from files that are already in git, so
storing the text again buys nothing: it can be regenerated by running the hook. What cannot be
regenerated is *what yesterday's block looked like* — and every serious defect this workspace has
had shows up in that shape rather than in the words.

Measured on this repository, 2026-09-07: the full block is 8,938 bytes and this record is 188. At
twenty sessions a day that is 62 MB a year against 1.3 MB. `tools/housekeeping.py` exists because
Claude Code's own data directories reached 950 MB unattended; a log that grows like the problem it
was written beside is not worth having, so this one is bounded by RECORD COUNT and stores no
content at all.

Three real defects from one day, and what each looks like here:

    rulecheck's glob raised out of the hook   -> "early": true, half the sections gone
    a tools index with a string `runs`        -> "bytes" drops by ~257, one section missing
    the downgrade banner lost its cap         -> "bytes" jumps to 34,728

None of those was noticed for hours. All three are obvious in a column of numbers.
"""
import json
import re

import tokens
import workspace as ws

LOG = "logs/block_shape.jsonl"
KEEP = 400          # records, not days: one session a day still leaves a year of trend
NAME_CHARS = 38     # a heading is an identifier here, not prose

_SECTION = re.compile(r"^### (.+)$", re.M)


def shape(body, ceiling=None, when=None, source=None, resent=True, dropped=(),
          index_behind=None, session=None, short=(), transcript=None, nonce=None):
    """The record for one assembled block. Pure: no clock, no disk, no workspace.

    🐛 [2026-09-09] `source` was not recorded, and it is the one dimension that makes the rest of
    this log answerable. SessionStart fires for five different reasons — startup, resume, compact,
    clear, fork — the hook already reads which, and it was discarded before reaching here. So a
    hundred and thirty-two records could be grouped by ceiling, by section set and by timestamp,
    and not by the question anybody actually asks of them: does a session that follows a compaction
    receive less than a fresh one. Costs one short string per record (R5 agent1, 2026-09-09).
    """
    sections = {}
    marks = list(_SECTION.finditer(body))
    for i, m in enumerate(marks):
        end = marks[i + 1].start() if i + 1 < len(marks) else len(body)
        sections[m.group(1).strip()[:NAME_CHARS]] = len(body[m.start():end].encode("utf-8"))
    # 🎯 [R3.3.10, 2026-09-16] `session` is the field that makes the rest of this log ANSWERABLE,
    # and it is the same lesson `source` above records. Without it, this log knows what a firing
    # dropped and `pointer.jsonl` knows which store a session opened, and NEITHER can answer the
    # question every eviction proposal needs: was a dropped section reopened later in the same
    # session? Joining them on a timestamp is a heuristic, not a key.
    #
    # Five banked items — GDSF ranking, Belady as a yardstick, PACMS, ARC's self-tuning split, and
    # the usage-recompute question — cannot be SCORED until this exists. Backfill is impossible
    # because old records do not carry it, so the clock starts when it is written, which is the
    # argument for writing it before the proposals rather than with them.
    #
    # Costs one short string per record. `source` cost the same and is now the dimension this log
    # is most often grouped by.
    # 🐛 [2026-09-21] (owner) Measured on a 152 MB transcript. The proof that a block is still in
    # this session's context looked for THIS session's fence, and the fence is derived from the
    # session id. A resume is usually handed a NEW session id -- 13 distinct ids across 18 firings
    # in one repository -- so the fence it searched for had never been written, the proof failed,
    # and the whole ~8.5 KB block was injected again on top of a conversation that already carried
    # it. Where the id DID repeat the proof worked: one session fired five times and shortened
    # three of them to nothing.
    #
    # So the fence has to be findable across an id change, and the only safe way is to remember the
    # ones WE emitted rather than to loosen what counts as a fence -- a repository file that could
    # forge one could suppress the block, which is the attack the unguessable marker exists to
    # stop. Keyed by transcript rather than by session because the transcript is what survives the
    # id change.
    rec = {"bytes": len(body.encode("utf-8")), "sec": sections,
           # The hook catches every exception and ends the block with this sentence rather than
           # failing, which is right — and is exactly why the truncation went unseen for hours.
           "early": "stopped early" in body,
           # 🐛 [2026-09-18] (R20.3) The block's token cost used to be derived from a fixed
           # bytes-per-token constant, measured 6% low on a block of mixed Thai and English.
           #
           # Same estimator every other caller in this package prices a block with
           # (`bin/chamnan-map`, `.chamnan/tools/session_block_size.py`) — script-weighted, so
           # Thai/CJK text is not priced as if it were plain Latin. Stored alongside `bytes` rather
           # than replacing it: `bytes` is the byte-for-byte size check, `tok` is the cost estimate.
           "tok": int(tokens.estimate(body))}
    if ceiling:
        rec["ceiling"] = ceiling
    if when:
        rec["t"] = when
    if source:
        rec["src"] = source
    if session:
        rec["session"] = session
    if transcript:
        rec["tr"] = str(transcript)[-120:]
    if nonce:
        rec["nc"] = str(nonce)
    if not resent:
        # A firing that proved the previous block is still in the transcript and printed a pointer
        # instead. There is no block to measure; the record exists so the log counts the session.
        rec["resent"] = False
    if index_behind:
        # 🐛 [2026-09-09] `index_is_behind` is computed on every single firing and thrown away, so
        # "how often has my index actually been stale this month" had no log to answer it from and
        # could only be re-derived by hand with a one-off script. One integer per record — seconds
        # behind — makes it a query. Recorded only when it IS behind, so a healthy log stays the
        # same size it is today (R5 agent 5, 2026-09-09).
        # The key is `behind`, not `index_behind` — the keyword argument and the record field have
        # different names, which is a trap for whoever greps the log first. And a record with NO
        # `behind` key means the index was current at that firing, not that staleness went
        # unmeasured: "how often was my index stale" is (records with the key) / (all records that
        # carry `sec`), never (records with the key) / (records that have it plus unknowns).
        rec["behind"] = int(index_behind)
    if dropped:
        # What the assembler BUILT and then cut. Without it the log records only what arrived, and
        # a section missing from every record is indistinguishable from a section this repository
        # does not have -- see `check()`, where reading the global list of possible sections instead
        # reported seven "never delivered" on a workspace that had none of them to deliver.
        rec["drop"] = sorted({str(d)[:NAME_CHARS] for d in dropped})
    # 🐛 [2026-09-20] (self-measured) `drop` is one of two ways a section fails to arrive whole, and
    # it was the only one recorded. The other -- reduced to its NAMES because the full text would
    # not fit -- is what 1.27.0's headline feature does, happens far more often than an outright
    # drop, and left no trace: on this repository `drop` fires on 16% of firings for a single
    # section, while a block sitting at 99.9% of its ceiling was reducing six at once with nothing
    # to say so afterwards. Same shape as `drop` so the two can be counted together or apart.
    if short:
        rec["short"] = sorted({str(s)[:NAME_CHARS] for s in short})
    return rec


def record(root, body, ceiling=None, when=None, source=None, resent=True, dropped=(),
           index_behind=None, session=None, short=(), transcript=None, nonce=None):
    """Append one shape record, trimmed to KEEP. Returns True when it wrote.

    Never raises: a session that cannot write its own telemetry is still a session, and the block
    has already been assembled by the time this is called. Skips entirely when another process
    holds the lock — two sessions starting in the same second is ordinary, and a dropped record is
    a cheaper outcome than an interleaved file.
    """
    # The bounded append itself lives in `workspace.append_jsonl` since 2026-09-10 — it was written
    # here first, and a second caller (the Agent-result hook) would have made it the eighth function
    # body in this package written in more than one file, in the package that counts them.
    return ws.append_jsonl(root, LOG, shape(body, ceiling, when, source, resent, dropped,
                                            index_behind, session, short, transcript, nonce), KEEP)



# How many earlier records a judgement is made against. Ten sessions is a few days of ordinary
# use — long enough that one unusual block does not move the median, short enough that a section
# deliberately switched off last week is not still expected today.
WINDOW = 10
# Below this share of the trailing median, a block did not get smaller, something went missing.
# Chosen from the defect it is named for: a tools-index bug dropped ~257 bytes from an ~8,900-byte
# block, which is 3% of it — anything remotely near half is far past ordinary variation.
COLLAPSE_SHARE = 0.5
# A section has to have been there for at least this share of the window before its absence counts
# as a loss. Without it, a section that appeared once is reported as "dropped" on the very next run.
PRESENT_ENOUGH = 0.5


def check(root, window=WINDOW, delivery_only=False):
    """What changed about the SHAPE of the last block that a person would want told.

    `delivery_only` keeps the two findings that mean THIS FIRING went wrong — the block was cut
    mid-build, or it collapsed against its own recent size — and drops the two that describe a
    standing condition. The distinction is the caller's audience, not the finding's importance.
    `chamnan-report` is run by a person asking "how is this workspace doing", and "five sections
    have never once arrived" is exactly what they came for. The session-start hook is not: a
    standing fact repeated at the top of every block forever is the per-firing cost 1.26 forbids,
    and the first version of that wiring shipped it for about four minutes (2026-09-12).

    A list of sentences, empty when there is nothing to say — the silence-on-no-news convention
    `pointer.py` and `ledger.py` already keep. Judged against the records before it rather than
    against a fixed number, because "8,900 bytes" is normal for one repository and impossible for
    another.

    🐛 [2026-09-08] This module's docstring names three real defects, each unnoticed for hours, and
    says they are "obvious in a column of numbers" — and nothing ever looked at the column.
    `chamnan-report` printed the sizes and a ceiling warning, which catches a block growing TOO BIG
    and none of the three: a truncated block, a byte collapse, a section silently gone. Replayed
    over this repository's own 36 real records the three checks fire zero times, and substituting
    one field to recreate each defect fires exactly the right one (R7 agent 5, whose prototype this
    is).
    """
    records = trend(root, last=window + 1)
    if not records:
        return []
    now, prior = records[-1], records[:-1]
    out = []
    if now.get("early"):
        out.append("the last block stopped early — it was cut, not shortened, so everything "
                   "after the cut never reached the session")
    sizes = [r["bytes"] for r in prior if isinstance(r.get("bytes"), int)]
    size_now = now.get("bytes")
    if sizes and isinstance(size_now, int):
        ordered = sorted(sizes)
        mid = len(ordered) // 2
        median = ordered[mid] if len(ordered) % 2 else (ordered[mid - 1] + ordered[mid]) / 2
        if median and size_now < median * COLLAPSE_SHARE:
            out.append(f"the last block was {size_now:,} bytes against a recent median of "
                       f"{median:,.0f} — a {100 - int(size_now * 100 // max(median, 1))}% drop, which is "
                       f"content missing rather than content shrinking")
    if prior:
        seen = {}
        for r in prior:
            for name in (r.get("sec") or {}):
                seen[name] = seen.get(name, 0) + 1
        # Every section this workspace is known to produce: one it delivered at some point, or one
        # it built and cut. A name in neither is a section this repository does not have.
        known = set(seen) | {n for r in prior + [now] for n in (r.get("drop") or [])}
        floor = len(prior) * PRESENT_ENOUGH
        gone = sorted(n for n, c in seen.items()
                      if c >= floor and n not in (now.get("sec") or {}))
        # 🐛 [2026-09-09] A section had to have ARRIVED before its absence could be reported:
        # `c >= floor` is computed from a window that never saw it, so a section at 0 of 90 can
        # never satisfy it and never will while it stays at zero. Three sections on this repository
        # are in exactly that state — the tools index, recorded procedures, and decisions and
        # lessons — dropped on every real firing this log has recorded, and the detector has never
        # once said so, because from its point of view nothing changed. A regression detector that
        # cannot see a BASELINE failure reports the health of what already works (R5 agent1, 2026-09-09).
        #
        # Said once and quietly: this is a standing condition, not news, and the report it feeds
        # is read for what changed.
        #
        # 🐛 [2026-09-09] The known set was read from `fit.DROP_ORDER`, which is every section
        # chamnan CAN emit anywhere -- not every section THIS repository has. A workspace with no
        # skills, no recorded decisions and no session handoffs was told that seven sections had
        # never arrived, when there was nothing to deliver and nothing wrong. The log has to carry
        # the answer instead of the code guessing it, which is why `shape()` now records what was
        # built and cut.
        _never = sorted(n for n in known
                        if n not in seen and n not in (now.get("sec") or {}))
        if _never and len(prior) >= 5:
            _shown = ", ".join(_never[:3]) + (f", and {len(_never) - 3} more"
                                              if len(_never) > 3 else "")
            if not delivery_only:
                out.append(f"{len(_never)} section(s) have not arrived once in the last "
                           f"{len(prior) + 1} blocks — {_shown}. Not a regression: they have never "
                           f"been delivered, so nothing here will report them as lost")
        if gone and not delivery_only:
            out.append("section(s) the last block did not carry, having carried them in at least "
                       "half of the ten before it: " + ", ".join(gone))
    return out


def trend(root, last=10, resent_only=True):
    """The most recent records, oldest first. For `chamnan-report`, and for a person asking
    "did something change?" — which is the only question this log exists to answer.

    🐛 [2026-09-09] Records marked `resent: False` are left out by default. A firing that proved
    the previous block was still in the transcript sends nothing, so its `bytes` is 0 — and averaged
    into a size trend that reads as the block collapsing, which is one of the three defects
    `check()` above exists to raise. Recording those firings without filtering them here would have
    manufactured the alarm it was added to make possible. They are COUNTED, not measured:
    `resent_only=False` returns them for anybody asking how much of a day takes the cheap path,
    which is a question about sessions rather than about block shape (R5 agent1, 2026-09-09)."""
    try:
        log = ws.workspace(root) / LOG
        if not log.is_file():
            return []
        out = []
        for line in log.read_text(encoding="utf-8-sig", errors="replace").splitlines():
            try:
                one = json.loads(line)
            except (json.JSONDecodeError, RecursionError):
                continue
            if not isinstance(one, dict):
                continue
            if resent_only and one.get("resent") is False:
                continue
            out.append(one)
        return out[-last:]
    except OSError:
        return []
