"""Will an edit to this path still be there tomorrow?

Two ways it will not, and they are the same sentence to the person editing:

* **the file is generated** -- the next build overwrites it
* **the file is ignored and untracked** -- git will never keep it

chamnan already knew the first and used it only to shape `MAP.md`. `mapper.py:663` records the
exact failure that knowledge would have prevented, about chamnan's own commenter: *"advice writes a
comment under a DO NOT EDIT line, which the next `protoc` run discards."* The lesson was learned
for one agent and never passed to the one the user is running.

**`tracked` beats `ignored`, always.** A file git is tracking is kept whatever the ignore rules say,
and repositories really do track things inside `build/` and `dist/`. Warning there would be the
false positive that matters most, because the advice is *do not edit this* and following it wrongly
blocks real work. `mapper._tracked_ambiguous` exists for the same reason on the indexing side.

**`git check-ignore`, never a hand-read `.gitignore`.** `catalogs.py` carries the defect from
reading only the root one while a nested `.gitignore` had been ignoring the file all along. git
answers for nested files, global excludes and `.git/info/exclude` at once, and it is the same
answer the user gets.

**No minified-line-length heuristic, deliberately.** R113 measured GitHub Linguist calling a file
minified above an average line length of 110 characters and `scc` above 255 average bytes -- two
widely used tools disagreeing by 2.3x on one question. There is no number to adopt, so none is.
"""
import os
import subprocess

import mapper
import mdblock
import workspace as ws

# How far into a file a generated-by marker is looked for. `mapper.BOILERPLATE_WINDOW` is the
# same idea for descriptions; this is smaller because every convention that exists -- Go's spec,
# Roslyn's `<auto-generated>`, protoc, Dart -- puts the marker in the first few lines.
MARKER_LINES = 12
# How far into a line's own content a generated-file marker may sit and still be a BANNER rather
# than a sentence mentioning one. Measured, not chosen: four real banners put it at 0, 0, 1 and 0,
# and the prose that made this necessary put it at 16. See the note beside the check in
# `generated()` for what that prose was — this module's own docstring.
GENERATED_MARKER_COLUMN = 4
# A file larger than this is not read for a marker. The path rules above still apply to it.
MAX_SNIFF_BYTES = 200_000


def _rel(root, path):
    """`path` relative to `root`, or "" when it is not inside it.

    🐛 [2026-09-22] (self-measured) `os.path.relpath` on the raw strings returned `../../../..` for
    every file in a temporary directory on macOS, so the whole module was silently inert there:
    `/var` is a symlink to `/private/var`, the hook resolves the root and the harness does not
    resolve the file path, and the two never met. Both sides are resolved here for the same reason
    `workspace.inside` resolves both -- a repository reached through a symlinked parent is ordinary,
    not exotic.
    """
    try:
        r = os.path.realpath(str(root))
        p = os.path.realpath(str(path))
        rel = os.path.relpath(p, r).replace(os.sep, "/")
    except (ValueError, OSError):
        return ""
    return "" if rel == ".." or rel.startswith("../") else rel


def _git(root, args):
    """(returncode, stdout). `None` when git cannot answer at all, or cannot answer for `root`.

    🐛 [2026-09-22] (self-measured) The full gate caught this: `git -C <root>` without
    `git_can_speak_for` first runs against whatever repository is ABOVE the directory when `root`
    is not itself a checkout. The answer then comes from somebody else's history -- a nested
    checkout would be told its files are ignored, or not, on evidence about its parent. The same
    defect is recorded twice in `mapper.py` for the same reason, and the suite checks the whole
    population of `git -C` callers because of it.
    """
    if not ws.git_can_speak_for(root):
        return None, ""
    try:
        # One list literal with `*args` spread into it, never `[...] + args`. A concatenation is
        # a BinOp, and the sweep that asserts every subprocess call runs git or this interpreter
        # cannot read the head of a BinOp -- it reports the site as executing something unknown.
        # `chamnan_skill_pointer.py` carries the same note for the same reason.
        r = subprocess.run(["git", "-C", str(root), *args], capture_output=True, text=True,
                           encoding="utf-8", errors="replace", timeout=5)
        return r.returncode, r.stdout
    except ws.git_cannot_answer():
        return None, ""


def _unmarked_globs(root):
    """Patterns the repository has explicitly declared NOT generated, with `-linguist-generated`.

    `mapper._generated_globs` skips these lines and keeps no record of them, because for indexing
    it only ever needed the positive set. Here they have to WIN: somebody writes `-linguist-generated`
    precisely because they do edit that file despite whatever its header says -- a forked vendor
    file is the usual case -- and warning them on every edit is the noise that teaches a reader to
    scroll past every notice this plugin will ever emit.
    """
    pats = []
    try:
        for holder, name in mapper._gitattributes_files(root):
            f = (mapper.Path(root) / holder / name) if holder else (mapper.Path(root) / name)
            try:
                text = f.read_text(encoding="utf-8-sig", errors="replace")
            except OSError:
                continue
            for line in text.splitlines():
                line = line.strip()
                if not line or line.startswith("#") or "-linguist-generated" not in line:
                    continue
                pats.extend(mapper._scoped(holder, line.split()[0]))
    except Exception:
        return ()
    return tuple(pats)


def generated(root, path):
    """A reason string when the path is generated, else \"\".

    Path rules first, because they answer without opening the file -- Bazel decides the same
    question purely from the output path, and a file that does not exist yet (a Write creating one)
    can only be judged this way.
    """
    rel = _rel(root, path)
    if not rel or rel.startswith("../"):
        return ""
    try:
        off = _unmarked_globs(root)
        if off and mapper._is_generated(rel, off, fold=False):
            return ""          # the repository said so explicitly; it outranks every other signal
        pats = mapper._generated_globs(root)
        if pats and mapper._is_generated(rel, pats, fold=False):
            return "`.gitattributes` marks it `linguist-generated`"
    except Exception:
        pass
    try:
        if os.path.getsize(str(path)) > MAX_SNIFF_BYTES:
            return ""
        with open(str(path), "r", encoding="utf-8", errors="replace") as fh:
            head = "".join(next(fh, "") for _ in range(MARKER_LINES))
    except (OSError, ValueError):
        return ""
    m = mapper.GENERATED_MARKER.search(head)
    if not m:
        return ""
    # 🐛 [2026-09-22] (self-measured) This module flagged ITSELF, and it found me while I was
    # editing it. Its own docstring quotes `mapper.py:663` — *"advice written as a comment under a
    # DO NOT EDIT line, which the next protoc run discards"* — and that quotation sits on line 10,
    # inside the twelve this sniffs. The detector for generated files matched its own prose about
    # detecting generated files, which is the trap this repository already records as "a check that
    # reads its own source matches itself".
    #
    # It is a CLASS, not one file: any README about code generation, any linting doc, any comment
    # explaining why a marker matters gets the same treatment, and a warning that fires on a healthy
    # file teaches the reader to skip the one that matters.
    #
    # Separated by where the marker SITS rather than by whether it appears. A real banner is the
    # line — it starts at the head of the content, after the comment punctuation. A mention is
    # somewhere inside a sentence. Measured on four real banners and the false positive:
    # `// Code generated by protoc-gen-go. DO NOT EDIT.` 0, Django 0, `<auto-generated>` 1,
    # `@generated` 0, and the prose 16. Four leaves room for a lead-in nobody has thought of and
    # is nowhere near sixteen.
    _line_start = head.rfind("\n", 0, m.start()) + 1
    _content = head[_line_start:m.start() + 1].lstrip("#/*-!<; \t")
    if len(_content) - 1 > GENERATED_MARKER_COLUMN:
        return ""
    # Quote the LINE, not the regex match. `generated\s+by\s+\S` ends one character after "by",
    # so the match alone reads as `Generated by t` -- a quotation cut mid-word looks like a bug in
    # the notice rather than evidence for it.
    line = head[:m.start()].rsplit("\n", 1)[-1] + head[m.start():].split("\n", 1)[0]
    line = " ".join(line.split()).lstrip("#/*- \t")
    return "it says %s" % mdblock.as_quoted(line, 72)


def unkept(root, path):
    """A reason string when git will not keep an edit here, else \"\".

    Tracked wins over ignored, and a repository chamnan cannot ask returns \"\" -- an unanswerable
    question is not evidence of anything.
    """
    rel = _rel(root, path)
    if not rel or rel.startswith("../"):
        return ""
    # ONE git call, not two. `git check-ignore` consults the index by default, so a TRACKED file
    # inside an ignored directory is reported as not ignored -- which is the answer wanted, since
    # git keeps a tracked file whatever `.gitignore` says. The evidence that this is deliberate
    # rather than incidental is that `--no-index` exists to turn it off.
    #
    # An explicit `ls-files --error-unmatch` first was written here and removed: it produced the
    # same verdict on every case in the fixture, and a mutation that deleted it changed nothing,
    # which is the definition of a line that is not doing anything. It cost a second subprocess on
    # every Edit, on the hook's critical path. Check 214 asserts the git behaviour this now leans
    # on, so a version that changes it fails there instead of warning a user about a file git is
    # perfectly happy to keep.
    # 🐛 [2026-09-22] (self-measured) This warned on every edit inside a nested checkout, and it
    # found me: editing `Work-Mode/chamnan/lib/pointer.py` was reported as an edit git would not
    # keep, while chamnan's OWN repository was tracking the file and showing it as modified. The
    # outer repository ignores `Work-Mode/chamnan/` wholesale — correctly, because a nested
    # checkout is not its business — so `check-ignore` answered truthfully about the wrong
    # repository.
    #
    # `git_can_speak_for(root)` above does not catch it: it asks whether ROOT is a checkout, and
    # here it is. The question it cannot ask is whether the FILE belongs to a nearer one.
    #
    # The cost of getting this wrong is not a wrong answer once. Anyone with a submodule or a
    # vendored checkout gets the warning on every edit inside it, and this repository's own rule
    # says a warning that fires on a healthy artifact teaches the reader to skip the line — which
    # would cost the case this module exists for: the generated file whose edit really is thrown
    # away.
    #
    # Answered with the filesystem rather than a second `git` call: a `.git` between the file and
    # the root means another repository owns it, and what the outer one thinks is not evidence.
    if _nested_checkout_between(root, path):
        return ""
    code, _ = _git(root, ["check-ignore", "-q", "--", rel])
    if code is None:
        return ""
    if code == 0:
        return "git is ignoring it and is not tracking it"
    return ""


def _nested_checkout_between(root, path):
    """True when a `.git` sits between `path` and `root` — another repository owns this file.

    Walks the file's own directories upward and stops AT the root, so the root's own `.git` is not
    counted: that one is the repository being asked, not a nearer rival. Bounded by the walk
    itself, and any filesystem error answers False, which leaves the previous behaviour exactly.
    """
    try:
        r = os.path.realpath(str(root))
        here = os.path.dirname(os.path.realpath(str(path)))
        while here and here != r and here.startswith(r):
            if os.path.exists(os.path.join(here, ".git")):
                return True
            parent = os.path.dirname(here)
            if parent == here:
                break
            here = parent
    except (OSError, ValueError):
        return False
    return False


def verdict(root, path):
    """\"\" when the edit survives, else one sentence saying why it will not.

    Generated is reported before ignored: a generated file usually IS tracked, so the two are not
    alternatives, and being overwritten by the next build is the more surprising of the two.
    """
    try:
        why = generated(root, path)
        if why:
            return ("this file is generated — %s — so the next build discards an edit here. "
                    "Change whatever generates it instead." % why)
        why = unkept(root, path)
        if why:
            return ("git will not keep an edit here — %s. Move the file into the tree, or expect "
                    "the change to vanish." % why)
    except Exception:
        return ""
    return ""
