@echo off
rem Windows shim for `chamnan_subagent_start.py`. GENERATED by install/make_windows_shims.py -- do not edit this file;
rem edit the generator and re-run it. `install/make_windows_shims.py --check` reports drift.
rem
rem `chamnan_subagent_start.py` has no extension and starts with a POSIX shebang, so cmd.exe cannot run it: PATHEXT
rem never matches an extensionless name, and the shebang is just a comment there. This file has the
rem same base name, is found through PATHEXT, and hands the script to the Python launcher.
rem
rem `py -3` first because that is what the python.org installer puts on PATH and it selects the
rem newest 3.x; `python` second, for a Microsoft Store or conda install that ships no launcher.
setlocal
where py >nul 2>nul
if not errorlevel 1 (
    py -3 "%~dp0chamnan_subagent_start.py" %*
    exit /b %errorlevel%
)
python "%~dp0chamnan_subagent_start.py" %*
exit /b %errorlevel%
