#!/usr/bin/env python3
"""Generate a `.cmd` beside every extensionless command and hook, so Windows can run them.

Every chamnan command is an extensionless file starting with `#!/usr/bin/env python3`. That is how
a POSIX system knows what to do with it and is exactly what cmd.exe cannot use: no extension means
PATHEXT never matches, and a shebang is a comment to Windows.

A `.cmd` of the same base name solves it. It is found through PATHEXT, sits beside the real script,
and hands it to the Python launcher.

**Generated rather than hand-written, and checked by a test.** Eleven near-identical files are
exactly the set where one gets forgotten -- and the failure would be a command that works
everywhere except the one platform the shims exist for. `test_windows_shims` walks the tree and
fails if a shim is missing, stale, or orphaned.

    python3 install/make_windows_shims.py            write them
    python3 install/make_windows_shims.py --check    report drift, write nothing (exit 1 if any)
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

TEMPLATE = '''@echo off
rem Windows shim for `{name}`. GENERATED by install/make_windows_shims.py -- do not edit this file;
rem edit the generator and re-run it. `install/make_windows_shims.py --check` reports drift.
rem
rem `{name}` has no extension and starts with a POSIX shebang, so cmd.exe cannot run it: PATHEXT
rem never matches an extensionless name, and the shebang is just a comment there. This file has the
rem same base name, is found through PATHEXT, and hands the script to the Python launcher.
rem
rem `py -3` first because that is what the python.org installer puts on PATH and it selects the
rem newest 3.x; `python` second, for a Microsoft Store or conda install that ships no launcher.
setlocal
where py >nul 2>nul
if not errorlevel 1 (
    py -3 "%~dp0{name}" %*
    exit /b %errorlevel%
)
python "%~dp0{name}" %*
exit /b %errorlevel%
'''


def targets():
    """Every extensionless script that needs a shim, as (source, shim) pairs.

    `bin/` for the commands a person types, and `hooks/` too: a hook is launched by path by the
    host, and on Windows that path can be pointed at the shim when the bare one does not resolve.
    """
    for folder, pattern in (("bin", "chamnan-*"), ("hooks", "chamnan_*.py")):
        for path in sorted((ROOT / folder).glob(pattern)):
            if folder == "bin" and path.suffix:
                continue
            yield path, path.with_suffix(".cmd")


def main():
    check = "--check" in sys.argv
    drift = []
    wanted = set()
    for source, shim in targets():
        wanted.add(shim)
        text = TEMPLATE.format(name=source.name)
        if not shim.exists() or shim.read_text(encoding="utf-8") != text:
            drift.append(shim)
            if not check:
                shim.write_text(text, encoding="utf-8")
    # An orphan is the other half of the same problem: a command renamed leaves a shim pointing at
    # a file that no longer exists, and it fails only on Windows, only for that command.
    for folder in ("bin", "hooks"):
        for shim in sorted((ROOT / folder).glob("*.cmd")):
            if shim not in wanted:
                drift.append(shim)
                if not check:
                    shim.unlink()
    if check:
        for path in drift:
            print(f"  drift: {path.relative_to(ROOT)}")
        print(f"{len(drift)} shim(s) out of date" if drift else "shims are current")
        return 1 if drift else 0
    print(f"{len(list(targets()))} shim(s) written")
    return 0


if __name__ == "__main__":
    sys.exit(main())
