#!/usr/bin/env python3
"""How many of MAP.md's claims are still true? Probe-and-refine, without the LLM.

Two results frame this. Gloaguen et al. (ETH Zurich) found LLM-generated repository context files
REDUCED coding-agent success by about 3% while raising cost over 20%. Probe-and-Refine
(arXiv:2606.20512) then found the variable was not who wrote the file but whether anything checked
it: guidance validated by probing reached 33.0% resolve on SWE-bench Verified against 25.5%
unguided, p<0.001. Auto-generated guidance is a liability until something verifies it.

chamnan cannot run that procedure — it uses LLM calls, and there is no network here at runtime. But
MAP.md is not LLM prose either. It is a set of mechanical claims about the tree, and a mechanical
claim can be checked mechanically:

    path        the file it names still exists
    lines       the (NNNL) count matches the file today
    functions   the (NNfn) count matches the file's TOP-LEVEL definitions
    classes     the (NNcls) count matches
    symbols     each named function is still defined in that file
    totals      the header's file count matches the number of rows in the Quick Index

Nothing here needs a model, a network, or a tool call. Run it against the map a session was last
handed, not only against one you rebuilt a second ago. Note that `.chamnan/MAP.md` may be gitignored
-- it is in the repository this was written in -- so "the committed map" is not always a thing that
exists, and the file on disk is what matters either way.

Two calibration notes, both of which this probe got wrong first and had to be corrected against
chamnan's own definitions before any number here meant anything:

  * Rows are counted only inside the Quick Index. The `- **`path`**` shape appears in later sections
    too, and counting those made a correct header look like a 51-row inconsistency.
  * Function and class counts are TOP-LEVEL, via ast. A regex that also matches nested and
    method-level `def` scored chamnan at 60% when it was right and the probe was wrong. When a probe
    and the thing it probes disagree, the probe is the more likely suspect.

    python3 .chamnan/tools/map_claim_check.py [path/to/MAP.md] [--verbose]
"""
import ast
import re
import sys
from pathlib import Path

# 🐛 [2026-09-06] The README credits this path inside the PLUGIN for "2,329 of 2,329 true", and the
# file lived only in the workspace chamnan is developed in -- a number a reader was asked to trust,
# from a tool they could not run. It ships here now and defaults to the repository it is run from,
# so a clean clone reproduces the measurement against its own index rather than against ours.
ROOT = Path.cwd()

QUICK = re.compile(r"^- \*\*`([^`]+)`\*\*(?: \((\d+)L(?:, (\d+)fn)?(?:/(\d+)cls)?\))?")
# 🐛 The Quick Index groups its rows under a directory heading and prints the BARE FILENAME in
# each row -- chamnan-map has done that since 3d05ec3 (2026-09-02). This checker kept joining
# the bare name to the repository root, so every one of the 322 rows resolved to nothing and
# it reported "path 0.0%" and an overall 83.6% about a map that is, measured independently,
# 100% correct. A verification tool that raises a false alarm is worse than one that is
# missing: somebody either wastes a day on it or learns to ignore the number.
# Three days passed before anybody noticed, because nothing runs this file.
QUICK_DIR = re.compile(r"^\*\*`([^`]+)/`\*\*$")
DETAIL = re.compile(r"^## `([^`]+)`$")
SYMBOL = re.compile(r"^- `([A-Za-z_][A-Za-z0-9_]*)\(")
HEADER = re.compile(r"Generated by chamnan\. ([\d,]+) source file\(s\), ([\d,]+) characters\.")


def _top_level(src):
    """(functions, classes) defined at module level, counted the way chamnan counts them."""
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return None, None
    fns = sum(isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) for n in tree.body)
    cls = sum(isinstance(n, ast.ClassDef) for n in tree.body)
    return fns, cls


def _quick_index(text):
    """Just the Quick Index. Later sections use the same row shape for different content."""
    start = text.find("## Quick Index")
    if start < 0:
        return text
    nxt = [m.start() for m in re.finditer(r"^## ", text, re.M) if m.start() > start]
    return text[start:nxt[0]] if nxt else text[start:]


def _inside(root, rel):
    """`root / rel` when it stays inside `root`, else None.

    🐛 The two joins below took a path straight out of MAP.md and read it. A row reading
    `- **`../../../../../../etc/hosts`** (99L)` made this probe open that file and print its real
    line count — and `preflight.py` runs this on every commit, unconditionally, as one of its six
    checks. A map is repository text: it arrives with a clone, and this tool exists precisely
    because a map can be wrong, so it must not assume the map is honest about where it points.
    """
    try:
        base = root.resolve()
        target = (base / rel).resolve()
    except OSError:
        return None
    return target if target == base or base in target.parents else None


def check_map(map_path, root=ROOT, verbose=False):
    text = map_path.read_text(encoding="utf-8", errors="replace")
    results = {k: [0, 0, []] for k in
               ("path", "lines", "functions", "classes", "symbols", "totals")}

    def record(kind, ok, detail=""):
        results[kind][0] += 1
        if ok:
            results[kind][1] += 1
        elif len(results[kind][2]) < 40:
            results[kind][2].append(detail)

    # --- Quick Index rows: path, and the counts printed beside it -------------------------------
    seen_paths = []
    cur_dir = ""
    for line in _quick_index(text).splitlines():
        d = QUICK_DIR.match(line)
        if d:
            # "." is what mapper writes for the repository root, and joining it would produce
            # "./name" -- harmless on POSIX, and wrong in the reported path.
            cur_dir = "" if d.group(1) in (".", "") else d.group(1)
            continue
        m = QUICK.match(line)
        if not m:
            continue
        rel, lines_c, fn_c, cls_c = m.group(1), m.group(2), m.group(3), m.group(4)
        # A row under a heading names the file only; a row with a slash in it already carries its
        # own directory and is left alone, so this works on a map written either way.
        if cur_dir and "/" not in rel:
            rel = f"{cur_dir}/{rel}"
        p = _inside(root, rel)
        if p is None:
            record("path", False, f"{rel}: resolves outside the repository")
            continue
        seen_paths.append(rel)
        exists = p.is_file()
        record("path", exists, rel)
        if not exists:
            continue
        # Only Python is counted here. The claim is made for every language, but a regex that
        # scores its own accuracy on JavaScript would be measuring the regex, not the map.
        try:
            src = p.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if lines_c:
            record("lines", len(src.splitlines()) == int(lines_c),
                   f"{rel}: says {lines_c}L, has {len(src.splitlines())}L")
        if p.suffix == ".py":
            fns, cls = _top_level(src)
            if fn_c and fns is not None:
                record("functions", fns == int(fn_c), f"{rel}: says {fn_c}fn, has {fns}")
            if cls_c and cls is not None:
                record("classes", cls == int(cls_c), f"{rel}: says {cls_c}cls, has {cls}")

    # --- Full Detail: every named symbol should still be defined in its own file -----------------
    current, src = None, ""
    for line in text.splitlines():
        d = DETAIL.match(line)
        if d:
            current = d.group(1)
            p = _inside(root, current)
            if p is None:
                continue
            src = p.read_text(encoding="utf-8", errors="replace") if p.is_file() else ""
            continue
        if not current or not current.endswith(".py") or not src:
            continue
        s = SYMBOL.match(line)
        if s:
            record("symbols", f"def {s.group(1)}(" in src or f"def {s.group(1)} (" in src,
                   f"{current}: names {s.group(1)}(), not defined there")

    h = HEADER.search(text)
    if h:
        claimed = int(h.group(1).replace(",", ""))
        record("totals", claimed == len(seen_paths),
               f"header says {claimed} files, index lists {len(seen_paths)}")

    return results, len(seen_paths)


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    verbose = "--verbose" in sys.argv
    target = Path(args[0]) if args else ROOT / ".chamnan" / "MAP.md"
    if not target.is_file():
        print(f"no map at {target}")
        return 1

    # A map's claims are relative to the repository that map describes, which is not necessarily
    # the repository this script lives in. It used to resolve every path against its OWN root, so
    # pointing it at any other map reported every file missing -- and that made it impossible to
    # test against a fixture, which is part of why the parser breakage went three days unnoticed.
    # `<repo>/.chamnan/MAP.md` is where chamnan puts it, so two parents up is the repository.
    root = target.resolve().parents[1] if target.resolve().parent.name == ".chamnan" else ROOT
    results, n = check_map(target, root=root, verbose=verbose)
    print(f"{target}  —  {n:,} indexed file(s)\n")
    print(f"  {'claim':<12} {'checked':>8} {'true':>8} {'rate':>8}")
    tot = ok = 0
    for kind, (c, k, _) in results.items():
        tot += c
        ok += k
        rate = f"{k / c * 100:.1f}%" if c else "—"
        print(f"  {kind:<12} {c:>8,} {k:>8,} {rate:>8}")
    print(f"  {'ALL':<12} {tot:>8,} {ok:>8,} {ok / tot * 100 if tot else 0:>7.1f}%")

    for kind, (c, k, bad) in results.items():
        if bad:
            print(f"\n  {kind} — {c - k} false claim(s), first {len(bad)}:")
            for b in bad[: (40 if verbose else 8)]:
                print(f"    {b}")
    # 🐛 [2026-09-06] This returned 0 whatever it found, so it could not gate anything -- which is
    # half of why "nothing runs this file" was true for three days while its own parser was broken.
    # A checker that cannot fail is a report nobody is obliged to read. `chamnan-map --verify` is
    # the other half: it is now reachable by name instead of only by knowing the path (R17 agent 5).
    return 0 if ok == tot else 1


if __name__ == "__main__":
    # Recorded on every real run, so retention measures USE and not the file's mtime.
    # An edit is not a use: with 22 of 25 tools silent here, every one of them fell back
    # to mtime and read as fresh after any edit, which disabled the TTL entirely.
    sys.exit(main())
